# Generated by Django 2.1.7 on 2019-03-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedstock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('area', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=10)),
                ('module', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
                ('box', models.CharField(max_length=10)),
                ('feedstock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='feedstock.Feedstock')),
            ],
        ),
    ]
