# Generated by Django 2.1.7 on 2019-03-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='box',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
