# Generated by Django 2.1.7 on 2019-03-23 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedstock', '0002_feedstock_quantity'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedstockAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=10)),
                ('module', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
                ('box', models.CharField(blank=True, max_length=10, null=True)),
                ('feedstock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedstock.Feedstock')),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='feedstock',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
